spring:
  application:
    name: secure-vault

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/sentinel_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # File Upload Limits
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # --- EMAIL CONFIGURATION (Updated for Render/Cloud) ---
  mail:
    host: smtp.gmail.com
    port: 465                 # Changed to SSL Port (Fixes Timeout)
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtps           # Changed to secure SMTP
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true      # Forces SSL connection immediately
            trust: smtp.gmail.com
          starttls:
            enable: false     # Disable StartTLS because we are using SSL
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# --- FRONTEND URL ---
app:
  frontend:
    url: ${FRONTEND_URL}